# AI Image Reminders - Minimal Test
# Test package to isolate YAML issues

# Template Sensors
template:
  - sensor:
      name: "Test Sensor"
      unique_id: test_sensor
      state: "test"

# Automations
automation:
  - id: test_automation
    alias: "Test Automation"
    description: "Simple test automation"
    trigger:
      - platform: time
        at: "12:00:00"
    condition: []
    action:
      - service: persistent_notification.create
        data:
          title: "Test"
          message: "Test automation worked"

# Input Boolean
input_boolean:
  test_boolean:
    name: "Test Boolean"
    icon: mdi:test-tube
